# Generated by Django 4.1.3 on 2022-11-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent_register',
            name='approval_status',
            field=models.IntegerField(default=0),
        ),
    ]
