# Generated by Django 4.1.3 on 2023-02-12 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_alter_room_booking_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_booking',
            name='student_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='APP.student_register'),
        ),
    ]
