# Generated by Django 4.1.3 on 2022-12-04 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_hostel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='hostel_image',
        ),
    ]
