# Generated by Django 4.1.3 on 2023-02-16 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_alter_room_booking_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='reply',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='student_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.student_register'),
        ),
    ]
