# Generated by Django 4.1.3 on 2023-02-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_alter_complaint_reply_alter_complaint_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='reply',
            field=models.TextField(null=True),
        ),
    ]
