
from django.urls import path

from APP import views, adminviews

urlpatterns = [
    path('',views.mainpage,name='mainpage'),
    path('student',views.student,name='student'),
    path('parent',views.parent,name='parent'),

    path('admin1',views.admin1,name='admin1'),
    path('studentview',views.studentview,name='studentview'),
    path('parentview',views.parentview,name='parentview'),
    path('viewstudents',adminviews.viewstudents,name='viewstudents'),
    path('viewsparents',adminviews.viewsparents,name='viewsparents'),
    path('approve_student/<int:id>/',adminviews.approve_student,name='approve_student'),
    path('reject_student/<int:id>/',adminviews.reject_student,name='reject_student'),
    path('approve_parent/<int:id>/',adminviews.approve_parent,name='approve_parent'),
    path('reject_parent/<int:id>/',adminviews.reject_parent,name='reject_parent'),
    path('add_hostel', adminviews.add_hostel, name='add_hostel'),
    path('view_hostel', adminviews.view_hostel, name='view_hostel'),
    path('hostel_update/<int:id>/', adminviews.hostel_update, name='hostel_update'),
    path('hostel_delete/<int:id>/', adminviews.hostel_delete, name='hostel_delete'),
    path('add_food', adminviews.add_food, name='add_food'),
    path('view_food', adminviews.view_food, name='view_food'),
    path('food_update/<int:id>/', adminviews.food_update, name='food_update'),
    path('food_delete/<int:id>/', adminviews.food_delete, name='food_delete'),
    path('add_fee', adminviews.add_fee, name='add_fee'),
    path('view_fee', adminviews.view_fee, name='view_fee'),
    path('fee_update/<int:id>/', adminviews.fee_update, name='fee_update'),
    path('fee_delete/<int:id>/', adminviews.fee_delete, name='fee_delete'),
    path('add_notification', adminviews.add_notification, name='add_notification'),
    path('view_notification', adminviews.view_notification, name='view_notification'),
    path('notification_update/<int:id>/', adminviews.notification_update, name='notification_update'),
    path('notification_delete/<int:id>/', adminviews.notification_delete, name='notification_delete'),
    path('add_attendance', adminviews.add_attendance, name='add_attendance'),
    path('view_attendance', adminviews.view_attendance, name='view_attendance'),
    path('attendance_update/<int:id>/', adminviews.attendance_update, name='attendance_update'),
    path('attendance_delete/<int:id>/', adminviews.attendance_delete, name='attendance_delete'),
    path('student_view_hostel', views.student_view_hostel, name='student_view_hostel'),
    path('student_view_food', views.student_view_food, name='student_view_food'),
    path('add_complaint', views.add_complaint, name='add_complaint'),
    path('view_complaint', views.view_complaint, name='view_complaint'),
    path('complaint_update/<int:id>/', views.complaint_update, name='complaint_update'),
    path('complaint_delete/<int:id>/', views.complaint_delete, name='complaint_delete'),
    path('fee_view', views.fee_view, name='fee_view'),
    path('add_payment', views.add_payment, name='add_payment'),
    path('view_payment', views.view_payment, name='view_payment'),
    path('update_payment/<int:id>/', views.update_payment, name='update_payment'),
    path('delete_payment/<int:id>/', views.delete_payment, name='delete_payment'),
    path('payment_view', adminviews.payment_view, name='payment_view'),
    path('notification_view', views.notification_view, name='notification_view'),
    path('attendance_view', views.attendance_view, name='attendance_view'),
    path('add_review', views.add_review, name='add_review'),
    path('view_review', views.view_review, name='view_review'),
    path('update_review/<int:id>/', views.update_review, name='update_review'),
    path('delete_review/<int:id>/', views.delete_review, name='delete_review'),
    path('view_review_details', adminviews.view_review_details, name='view_review_details'),
    path('add_staff', adminviews.add_staff, name='add_staff'),
    path('view_staff', adminviews.view_staff, name='view_staff'),
    path('staff_update/<int:id>/', adminviews.staff_update, name='staff_update'),
    path('staff_delete/<int:id>/', adminviews.staff_delete, name='staff_delete'),
    path('parent_view_hostel', views.parent_view_hostel, name='parent_view_hostel'),
    path('student_view_staff', views.student_view_staff, name='student_view_staff'),
    path('parent_view_staff', views.parent_view_staff, name='parent_view_staff'),
    path('parent_attendance_view', views.parent_attendance_view, name='parent_attendance_view'),
    path('parent_add_payment', views.parent_add_payment, name='parent_add_payment'),
    path('parent_view_payment', views.parent_view_payment, name='parent_view_payment'),
    path('add_book_room', views.add_book_room, name='add_book_room'),
    path('view_room_booking', views.view_room_booking, name='view_room_booking'),
    path('admin_view_room_booking', adminviews.admin_view_room_booking, name='admin_view_room_booking'),
    path('update_roombooking/<int:id>/', views.update_roombooking, name='update_roombooking'),
    path('delete_roombooking/<int:id>/', views.delete_roombooking, name='delete_roombooking'),
    path('student_viewstudents', views.student_viewstudents, name='student_viewstudents'),
    path('parent_view_fee', views.parent_view_fee, name='parent_view_fee'),
    path('admin_view_complaint', adminviews.admin_view_complaint, name='admin_view_complaint'),
    path('admin_reply/<int:id>/', adminviews.admin_reply, name='admin_reply'),
    path('approve_roombooking/<int:id>/', adminviews.approve_roombooking, name='approve_roombooking'),
    path('reject_roombooking/<int:id>/', adminviews.reject_roombooking, name='reject_roombooking'),


]